Account/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutPage, name="logout"),
]

Chat/urls.py
from django.urls import path
from .views import ChatListView, ChatCreateView
app_name = 'chat'

urlpatterns = [
    path('', ChatListView.as_view(), name='all'),
    path('new/', ChatCreateView.as_view(), name='new'),
]

Setting/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("Account.urls")),
    path('chat/', include('Chat.urls')),
]

Account/models.py
from django.db import models

# Create your models here.


class Account(models.Model):
    date = models.DateTimeField()
    User_name = models.CharField(max_length=200)
    Password = models.CharField(max_length=200)
    content = models.TextField()

Chat/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.urls import reverse

# Create your models here.
# i have no what this is all about
User = get_user_model()


class Chat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    posted_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.message)

    def get_absolute_url(self):
        return reverse('chat:all')

Account/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# i don't actually really know why using this instead of just creating a model


class CreateUSerForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

Chat/forms.py
from django import forms
from .models import Chat


class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ['message']

Account/views.py
from django.shortcuts import render, redirect
from .forms import CreateUSerForm


# i need a message to say to the user if the account was created or not, django offer one function for that
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
# Create your views here.

from django.views.decorators.csrf import csrf_exempt

# it can be possible to go the home even though you didn't login yet, that's totally weird. let's change that
from django.contrib.auth.decorators import login_required


# be careful when you use this, don't put it everywhere
@ login_required(login_url='login')
def home(request):
    return render(request, "Account/home.html", {})


@ csrf_exempt
def loginPage(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        # now, let's use our authenticate. this is another one. really i don't how to use this as well
        user = authenticate(request, username=username, password=password)

        # maybe, it's for checking that the user is not None
        if user is not None:
            login(request, user=user)
            return redirect("accounts:home")
        else:
            messages.info(request, 'Username or Password is incorrect')

    context = {}
    # don't never forget to put return, hahaha
    return render(request, "Account/login.html", context)


@ csrf_exempt
def logoutPage(request):
    logout(request)
    return redirect('accounts:login')


@ csrf_exempt
def register(request):
    form = CreateUSerForm()
    if request.method == "POST":
        form = CreateUSerForm(request.POST)

        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect('accounts:login')

    context = {"form": form}
    return render(request, "Account/register.html", context)

Chat/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView
from .forms import ChatForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Chat
from django.utils import timezone
from django.urls import reverse
# Create your views here.


class ChatCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:login'
    form_class = ChatForm
    model = Chat

    # what is this

    def form_valid(self, form):
        my_message = form.save(commit=False)
        my_message.user = self.request.user
        my_message.save()
        return super().form_valid(form)


class ChatListView(LoginRequiredMixin, ListView):
    model = Chat
    context_object_name = "mess"

    def get_queryset(self):
        return Chat.objects.filter(posted_at__lte=timezone.now()).order_by('posted_at')

Chat/templates/Chat/chat_form.html
{% extends 'Account/home.html' %}

{% block content %}
    <form method="POST">
    	{% csrf_token %}
    	{{ form.as_p }}

    	<br><input type="submit" value="Post" class="btn btn-lg btn-outline-primary">
    </form>
{% endblock content %}

Chat/templates/Chat/chat_list.html
{% extends 'Account/home.html' %}

{% block content %}
{% for chat in mess %}

    	<div class="chat bg-primary" style="width: 50%; border-radius: 40px; ">
			<div class="ml-5" style="color: white;">
					<p><b class="chat-content">{{ chat|linebreaks }}</b></p>
				<small class="chat-date">Posted on {{ chat.posted_at }} by</small>
			{% if chat.user.is_superuser %}


    		    <small class="chat-user-special text-capitalize "> {{ chat.user }}- Admin </small>


    		{% else %}

						<small class="chat-user text-capitalize"> {{ chat.user }} </small>

    		{% endif %}


			</div>

    	</div><br>

    {% empty %}
    <h1 class="heading">No Chats Yet Be The First To Message!</h1><br>

    {% endfor %}

<div class="fixed-bottom form-inline">
	<form method="POST" action="{% url 'chat:new' %}">
    	{% csrf_token %}
		<input type="text" class="form-control ml-2 mr-2" style="width: 1000px;" name="message" placeholder="Write a message">
    	<input type="submit" value="Send" class="btn btn-lg btn-outline-primary">
    </form>


</div>
{% endblock %}